name: Docs
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install -y libcriterion-dev libcriterion3

      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - run: pip install -r docs/requirements.txt
      - run: mkdir build
      - run: cmake -B build/

      - name: Build Docs
        run: cmake --build build --target docs
