name: Lints
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install -y libcriterion-dev libcriterion3

      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - run: mkdir build
      - run: cmake -B build/

      - name: Run Lints
        run: cmake --build build/ --target lint
